security: 
  basic: 
    enable: false
server: 
  context-path: /auth
  port: 8281
spring: 
  application: 
    name: oauth2-test
  datasource: 
    password: password
    url: "jdbc:mysql://localhost:3306/test-oauth2"
    username: root
  jpa: 
    hibernate: 
      ddl-auto: none
  profiles: 
    active: develop