security: 
  basic: 
    enable: false
server: 
  context-path: /auth
  port: 8281
spring: 
  application: 
    name: oauth2-test
  jpa: 
    hibernate: 
      ddl-auto: none
  profiles: 
    active: develop