spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?useSSL=false
    username: root
    password: admin1234
    driver-class-name: com.mysql.jdbc.Driver   
  jpa:
    properties:
      hibernates:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
