spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-oauth2?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver   
  jpa:
    properties:
      hibernates:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
