# Spring DATASOURCE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-api-employee?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver   

#HIBERNATE PROPERTIES
spring:
  jpa:
    properties:
      hibernates:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#HIBERNATE DDL AUTO
spring:
  jpa:
    hibernate:
      ddl-auto: update